### ISSUE TITLE
I have a problem with internal error!

### ISSUE THREAD

**Issue by Froggyp** [messageofdeath/PaidRanks#3]
This is the error message:
org.bukkit.command.CommandException: Unhandled exception executing command 'rankup' in plugin PaidRanks v3.7
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit-1.10.jar:git-Bukkit-10c10b3]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit-1.10.jar:git-Bukkit-10c10b3]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:625) ~[craftbukkit-1.10.jar:git-Bukkit-10c10b3]
	at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1296) [craftbukkit-1.10.jar:git-Bukkit-10c10b3]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1156) [craftbukkit-1.10.jar:git-Bukkit-10c10b3]
	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(SourceFile:37) [craftbukkit-1.10.jar:git-Bukkit-10c10b3]
	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(SourceFile:9) [craftbukkit-1.10.jar:git-Bukkit-10c10b3]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.10.jar:git-Bukkit-10c10b3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [craftbukkit-1.10.jar:git-Bukkit-10c10b3]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:690) [craftbukkit-1.10.jar:git-Bukkit-10c10b3]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:360) [craftbukkit-1.10.jar:git-Bukkit-10c10b3]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:646) [craftbukkit-1.10.jar:git-Bukkit-10c10b3]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:550) [craftbukkit-1.10.jar:git-Bukkit-10c10b3]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NullPointerException
	at me.messageofdeath.PaidRanks.Utils.API.PaidRanksAPI.getGroups(PaidRanksAPI.java:110) ~[?:?]
	at me.messageofdeath.PaidRanks.Commands.RankupCommand.rankup(RankupCommand.java:94) ~[?:?]
	at me.messageofdeath.PaidRanks.Commands.RankupCommand.issue(RankupCommand.java:47) ~[?:?]
	at me.messageofdeath.PaidRanks.Utils.zRequired.Commands.CommandListener.onCommand(CommandListener.java:15) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit-1.10.jar:git-Bukkit-10c10b3]
	... 15 more

**Comment by messageofdeath** [comment]
This is probably due to you not having a compatible permissions plugin. I'm going to see about adding Vault back as at the time I was getting back into development and I thought Vault was discontinued. For now these are the plug-ins that are compatible.
Economy:
The New Economy
SQLEconomy
iConomy
Permissions:
PermissionsEx
LuckPerms
